name: CLI Tests

on:
  push:
    paths:
      - 'cli/**'
  pull_request:
    paths:
      - 'cli/**'

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x]

    steps:
      - uses: actions/checkout@v3
      
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
          cache-dependency-path: './cli/package-lock.json'
          
      - name: Install dependencies
        working-directory: ./cli
        run: npm install
        
      - name: Run tests
        working-directory: ./cli
        run: npm test
