name: autofix.ci
on:
  pull_request:
  push:
permissions: {}
jobs:
  prettier:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
      - run: |
          npm install
          npx prettier ./cli/ --check --ignore-unknown
      - uses: autofix-ci/action@v1
        with:
          commit-message: "Apply Prettier format"